### ISSUE TITLE
Class::MOP::load_class is deprecated

### ISSUE THREAD

**Issue by chiselwright** [SPORE/net-http-spore#32]
According to https://metacpan.org/pod/release/ETHER/Moose-2.1200/lib/Class/MOP.pm#Metaclass-cache-functions:

```
Some utility functions (such as Class::MOP::load_class) that were previously defined in Class::MOP regarding loading of classes have been extracted to Class::Load. Please see Class::Load for documentation.
```

This is a fairly simple fix; pull-request to follow.

**Comment by a3f** [comment]
> Also Net::HTTP::Spore should depend on MooseX::Role::Parameterized version 1.01.

Fixed in 1364c6827d8d5a5028e6bdd176f8915453845e1f. CPAN Release will follow soon.
